### ISSUE TITLE
Volumes mounted with docker-compose are empty

### ISSUE THREAD

**Issue by bryannaegele** [Parallels/docker-machine#6]
Any volume I mount in docker-compose.yml results in an empty directory being mounted. If the volume is added to the image during the build step and volumes are omitted from docker-compose, the files are present. 

Given Dockerfile:
```
FROM nodesource/trusty:4.0.0

RUN mkdir /dist
COPY package.json /dist/package.json
RUN cd /dist && npm install && npm install pm2 -g

ADD . /app

EXPOSE 8080

CMD [ "pm2", "start app-dev.json --no-daemon" ]
```

and 

docker-compose.yml
```
web:
  build: ./
  dockerfile: Dockerfile
  ports:
    - "8080:8080"
  expose:
    - "8080"
  working_dir: /app
  volumes:
    - .:/app
  environment:
    NODE_PATH: /dist/node_modules
  command: "tail -f /dev/null"
```

`/app` will be present but empty.

Removing volumes from compose - `/app` will be present and contain the files from the local directory.

Leaving volumes in compose and removing `ADD . /app` from Dockerfile - `/app` will be present but empty.

Am I missing an important step or concept here? I am attempting to replicate my docker/vagrant setup of mapping my local code directory into the container for hotloading my code changes during dev and I'm failing.

Thanks for your help.

**Comment by bryannaegele** [comment]
I ended up destroying the vm completely and firing up a fresh one from scratch and it works as expected with no changes. The only change I had made to the previous VM was to stop it and use the Parallels GUI (v11 Pro) to update the cpu and memory allocations. I can't imagine that had any effect. I did try mounting volumes doing a normal `docker run` to rule out compose and had the same broken behavior.

I will close for now but would love any insight if you have any ideas on what would cause the behavior I described. The only thing I could think of is if somehow the volume driver was changed somehow which would prevent path expansion. The other would be some type of file corruption.

**Comment by SwithFr** [comment]
Hum,  I think I have the same issue... 

My app structure : 
```
myapp :
    - bin
        - server.js
    - node_modules
    ...
```

```yml
app:
    build: ./docker/app
    ports:
        - "27615:27615"
    environment:
        APP_PORT: 27615
        NODE_ENV: "development"
    volumes:
        - ".:/src/app"
    volumes_from:
        - data
    command: supervisor -w bin -e js,jade -i docker,node_modules,src,static bin/server.js
    links:
        - "database:postgres"
```

But when I run `docker-compose build up` and I inspect my app container : 

`Error: Cannot find module '/src/app/bin/server.js'` so I guess that the /src/app is empty 

I have already created a fresh VM but it still doesn't work :'(
